# Idempotent Aurora schema alignment for production (wiley-co-aurora-db-encrypted).
# Skips EF migration FK refresh blocks that fail on hybrid legacy constraint names.
# Applied via: pwsh ./Scripts/apply-aurora-schema-alignment-idempotent.ps1

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM "Charges"
        WHERE COALESCE("UtilityBillId", 0) = 0 AND COALESCE("BillId", 0) = 0
    ) THEN
        RAISE EXCEPTION 'Charges row(s) missing BillId/UtilityBillId';
    END IF;
END $$;

UPDATE "Charges"
SET "UtilityBillId" = "BillId"
WHERE ("UtilityBillId" IS NULL OR "UtilityBillId" = 0) AND "BillId" IS NOT NULL;

ALTER TABLE "Charges" DROP CONSTRAINT IF EXISTS "FK_Charges_UtilityBills_BillId";

DROP INDEX IF EXISTS "IX_Charges_BillId";

ALTER TABLE "Charges" DROP COLUMN IF EXISTS "BillId";

ALTER TABLE "Charges" ALTER COLUMN "UtilityBillId" SET NOT NULL;

ALTER TABLE "BudgetInteraction" DROP CONSTRAINT IF EXISTS "FK_BudgetInteraction_Enterprises_EnterpriseId";

ALTER TABLE "BudgetInteraction" DROP COLUMN IF EXISTS "EnterpriseId";

ALTER TABLE "UtilityCustomers" ADD COLUMN IF NOT EXISTS "EnterpriseId" integer NULL;

CREATE INDEX IF NOT EXISTS "IX_UtilityCustomers_EnterpriseId" ON "UtilityCustomers" ("EnterpriseId");

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS applied_allocation_profile_id bigint NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS applied_allocation_profile_name character varying(200) NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS applied_routing_rule_id bigint NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS applied_routing_rule_name character varying(200) NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS original_entry_scope character varying(100) NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS routing_allocation_percent numeric(18,2) NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS routing_reason character varying(500) NULL;

ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS source_amount numeric(18,2) NULL;

CREATE INDEX IF NOT EXISTS "IX_ledger_entries_entry_scope" ON ledger_entries (entry_scope);

CREATE INDEX IF NOT EXISTS "IX_BudgetEntries_SourceFilePath" ON "BudgetEntries" ("SourceFilePath");

CREATE INDEX IF NOT EXISTS "IX_AuditEntries_Timestamp" ON "AuditEntries" ("Timestamp");

CREATE INDEX IF NOT EXISTS "IX_AuditEntries_EntityType_EntityId_Timestamp" ON "AuditEntries" ("EntityType", "EntityId", "Timestamp");

CREATE TABLE IF NOT EXISTS "ApartmentUnitTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EnterpriseId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "BedroomCount" integer NOT NULL,
    "UnitCount" integer NOT NULL,
    "MonthlyRent" numeric(18,2) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone NULL,
    "CreatedBy" text NULL,
    "ModifiedBy" text NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedDate" timestamp with time zone NULL,
    "DeletedBy" text NULL,
    CONSTRAINT "PK_ApartmentUnitTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApartmentUnitTypes_Enterprises_EnterpriseId" FOREIGN KEY ("EnterpriseId") REFERENCES "Enterprises" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ApartmentUnitTypes_EnterpriseId_Name" ON "ApartmentUnitTypes" ("EnterpriseId", "Name");

CREATE TABLE IF NOT EXISTS quickbooks_allocation_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    description character varying(500) NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_quickbooks_allocation_profiles" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS "IX_quickbooks_allocation_profiles_is_active" ON quickbooks_allocation_profiles (is_active);

CREATE TABLE IF NOT EXISTS quickbooks_allocation_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    allocation_profile_id bigint NOT NULL,
    enterprise_name character varying(100) NOT NULL,
    allocation_percent numeric(18,2) NOT NULL,
    CONSTRAINT "PK_quickbooks_allocation_targets" PRIMARY KEY (id),
    CONSTRAINT "FK_quickbooks_allocation_targets_quickbooks_allocation_profiles_allocation_profile_id" FOREIGN KEY (allocation_profile_id) REFERENCES quickbooks_allocation_profiles (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_quickbooks_allocation_targets_allocation_profile_id" ON quickbooks_allocation_targets (allocation_profile_id);

CREATE TABLE IF NOT EXISTS quickbooks_routing_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    description character varying(500) NULL,
    priority integer NOT NULL,
    is_active boolean NOT NULL,
    source_file_pattern character varying(200) NULL,
    default_enterprise_pattern character varying(200) NULL,
    account_pattern character varying(200) NULL,
    memo_pattern character varying(200) NULL,
    name_pattern character varying(200) NULL,
    split_account_pattern character varying(200) NULL,
    target_enterprise character varying(100) NULL,
    allocation_profile_id bigint NULL,
    CONSTRAINT "PK_quickbooks_routing_rules" PRIMARY KEY (id),
    CONSTRAINT "FK_quickbooks_routing_rules_quickbooks_allocation_profiles_allocation_profile_id" FOREIGN KEY (allocation_profile_id) REFERENCES quickbooks_allocation_profiles (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_quickbooks_routing_rules_allocation_profile_id" ON quickbooks_routing_rules (allocation_profile_id);

CREATE INDEX IF NOT EXISTS "IX_quickbooks_routing_rules_is_active" ON quickbooks_routing_rules (is_active);

CREATE INDEX IF NOT EXISTS "IX_quickbooks_routing_rules_priority" ON quickbooks_routing_rules (priority);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_UtilityCustomers_Enterprises_EnterpriseId'
    ) THEN
        ALTER TABLE "UtilityCustomers"
            ADD CONSTRAINT "FK_UtilityCustomers_Enterprises_EnterpriseId"
            FOREIGN KEY ("EnterpriseId") REFERENCES "Enterprises" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260525204607_SchemaAlignmentProductionReadiness', '9.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260525204607_SchemaAlignmentProductionReadiness'
);
